Add checks for secret passwort in GIT

diff --git a/workflows/Playwright-tests.yml b/workflows/Playwright-tests.yml
--- a/workflows/Playwright-tests.yml
+++ b/workflows/Playwright-tests.yml
@@ -24,6 +24,23 @@ jobs:
       - name: install Playwright browsers
         run: npx playwright install --with-deps
 
+      - name: Check environment variables
+        run: |
+          if [ -z "$BASE_URL" ]; then
+            echo "BASE_URL is missing"
+            exit 1
+          else
+            echo "BASE_URL is available"
+          fi
+
+          if [ -z "$TEST_PASSWORD" ]; then
+            echo "TEST_PASSWORD is missing"
+            exit 1
+          else
+            echo "TEST_PASSWORD is available"
+          fi
+
+
       - name: Run Playwright tests
         run: npx playwright test
 
